### ISSUE TITLE
inet4.xdd blocks floppy formatting

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#117]
I saw a bug report + workaround about this in our local Czech/Slovak mailing list. Apparently if you have inet4.xdd active, floppy formatting under FreeMiNT doesn't work.

Teradesk says "floppy device can not be locked for xbios operations", Kobold/E-COPY says that the floppy drive is used by another application.

I don't have a floppy drive in my Falcon for a long time so I can't test, can someone?

**Comment by DavidGZ** [comment]
I've just tested it and I confirm that formatting a floppy in Teradesk and Kobold doens't work when inet4.xdd is loaded.

**Comment by skaftetryne** [comment]
This has been a problem for 15 years or more. When I looked into this years ago it turned out that it was syslogd that held a lock on the floppy. Killing syslogd allowed me to format the floppy. Apparently Alan tried to fix this back in 2011:

https://mikro.naprvyraz.sk/mint/201107/threads.html#00296

I'm sure I wrote about my findings on the MiNT-list, but I could not find that thread.

**Comment by mikrosk** [comment]
Oh yes, it's an old one. The mentioned file can be found here: https://mikro.naprvyraz.sk/gentoo.atariforge.org/files/app-admin/sysklogd-1.5.tbz2 but it's not so much help even if it work because @atic-atac hasn't provided any source code to his gentoo packages...

**Comment by skaftetryne** [comment]
mikrosk, what was the suggested workaround you mention? Booting with no inetd.xdd?

IIRC I investigated this problem sometime around 2010 after a bug report by Peter Slegg. Dlock() said that syslogd held a lock on the floppy device. Killing syslogd allowed formatting from Thing! under XaAES/MiNT. It was a bit strange, as the floppy was otherwise working normally. I would assume that if it really was locked it would not be possible to access it, as Dlock would prevent GEMDOS operations on that device.

**Comment by mikrosk** [comment]
> what was the suggested workaround you mention? Booting with no inetd.xdd?

Yes. I have asked the guy to try to kill syslogd and/or the new sysklogd archive to see whether it helps in his case.

**Comment by skaftetryne** [comment]
If you don't enable inetd.xdd syslogd will not start as socket functionality is missing. However, I'm not sure if syslogd is the root of the problem here. Floppy behaviour is odd - as I said it should not be possible to access the floppy drive at all when a process has Dlock-ed it (after all, the purpose is to lock the drive for GEMDOS access when a process is doing low level access) but you can read and write files/directories.

**Comment by mikrosk** [comment]
Of course, the idea was to kill/replace with inetd.xdd enabled. And I agree, something strange is going on. Maybe it's reproducible in Aranym, too? That would help with debugging.

**Comment by mikrosk** [comment]
I wanted to give it a try under Hatari and Aranym but no luck, it seems that floppy formatting isn't very good in those emulators. So @DavidGZ, if you feel like looking into it, go ahead.

**Comment by skaftetryne** [comment]
I just tested on my Falcon/CT60e which is running a 1.19 from 2017. It runs a plain GEM-focused setup so no inetd or syslogd, but inetd.xdd is loaded and network set up with dhclient. I was allowed to format a floppy from Teradesk without issues.

**Comment by skaftetryne** [comment]
@mikrosk, it's not necessary to actually format a disk to test this. If you get as far as (attempting to) format the problem in question is not present. From what I can see the problem is that Dlock say that the floppy is locked, which is why Teradesk/Thing!/whatever formatter throws an error and refuses to format.

**Comment by mikrosk** [comment]
@skaftetryne the guy confirmed that his 1.19 from April 2018 doesn't work. Can you try current snapshot on your Falcon? (I asked him the opposite, to try your VanillaMiNT from 2017).

**Comment by skaftetryne** [comment]
Not now, I'm in the middle of a complete kitchen renovation and have way too little time for playing I'm afraid. Maybe this weekend, I'm hoping to take a few hours off then.

**Comment by skaftetryne** [comment]
Btw did that guy test by killing syslogd, or by not starting it in the first place? I assume he's using EasyMiNT, he should try to not run init but start XaAES directly and then test.

**Comment by DavidGZ** [comment]
I've done some more tests, syslogd seems to have no influence in this problem, with the version 1.5 linked above the problem persists, and even it's still there with no syslogd running.
If I run xaaes directly from mint.cnf instead of init, then I'm able to format.
All this with current kernel.

**Comment by mikrosk** [comment]
OK so if I understand your and Jo's description correctly, inet4.xdd can be loaded but you have to start `xaloader` instead of `/sbin/init`? I guess `/sbin/init` somehow messes with logging and leads to this situation. That would explain all the confusing reports over the years, it worked for some (like Jo) while it never worked for someone else (like the Czech guy using /sbin/init).

**Comment by DavidGZ** [comment]
>OK so if I understand your and Jo's description correctly, inet4.xdd can be loaded but you have to start xaloader instead of /sbin/init?

Yes if you run xaloader from mint.cnf, if you run it from /etc/ttyab I'm sure it won't work.

It must be something loaded by the SpareMiNT init scripts and it seems that is inetd, if you kill inetd  then format works agin, now we need to figure out why. I guess not loading inet4.xdd makes inetd to fail and the problem disappears.

**Comment by DavidGZ** [comment]
>I'm sure I wrote about my findings on the MiNT-list, but I could not find that thread.

I think I've found it:
https://mikro.naprvyraz.sk/mint/200912/msg00325.html

**Comment by skaftetryne** [comment]
@DavidGZ Thanks! So the problem is not that some process has *locked* the floppy, but that Dlock (which any program that wants to format a disk should use to prevent other access to the floppy while formatting is in process) fails because some process has an open file on it. That makes sense, as GEMDOS access to the floppy is not affected.

So some process run by init opens a file or directory on the floppy (maybe it opens u:\a?) but does not close it again. We have seen two examples here, syslogd (from my findings) and inetd (David's findings). The actual process may the accidental, it doesn't necessarily has to have opened this file/directory itself but could have inherited it from a parent.

**Comment by vinriviere** [comment]
Note that the Fsfirst() / Fsnext() API is wrong by design, as there is no way to "close" the directory search. Systems implementing it (TOS, EmuTOS, FreeMiNT, GEMDOS drive emulation in emulators...) need to use some heuristics to close the associated resources. I.e. close them on the last Fsnext(). So that API is very likely to cause resource leaks. I don't say this is what happens here, that's just a hint.

**Comment by DavidGZ** [comment]
>The actual process may the accidental, it doesn't necessarily has to have opened this file/directory itself but could have inherited it from a parent.

Yes the process is accidental, if I comment the line for the ftp service in inetd.conf the process owning the open handle becomes portmap.

I think it could be something wrong with how the kernel handles the opened files list of processes. Thant list have pointers to the fcookie struct [1] that identifies the files. The opened file that makes Dlock to reject the locking attempt has always an "index" value 0 in the fcookie struct , I didn't have time to check how those indexes are generated but I think it's a strange number for an index, all the indexes in the opened files list that I have checked are random long numbers. Note too that by chance the device number ("dev" member in fcookie struct) for the floppy drive(a:) is also 0,  I don't discard some entry in the open files list got messed up.

I'll investigate further as soon as I have some more time.

[1] https://github.com/freemint/freemint/blob/a3af9bdb97c0c5b10114177dfedadbc52df7f373/sys/mint/fsops.h#L19

**Comment by th-otto** [comment]
On Donnerstag, 9. Mai 2019 13:20:13 CEST Vincent Rivière wrote:

>Note that the Fsfirst() / Fsnext() API is wrong by design,

Yes, one of the annoying things that date back to CP/M times.

> systems implementing it (TOS, EmuTOS, FreeMiNT, GEMDOS drive emulation in
> emulators...) need to use some heuristics to close the associated
> resources.

TOS & EmuTOS should not be affected, since all information is stored in the 
DTA only, and no resources are allocated for this. In emulators, that *might* 
leak some resources on the host, but should not affect the calling OS. The 
usual way to handle that "heuristic" is to a) close the directory if Fsnext 
reports no more files and b) immediately close it if Fsfirst does not use any 
wildcards. IIRC correctly, FreeMiNT handles that similarly.

**Comment by th-otto** [comment]
On Donnerstag, 9. Mai 2019 13:55:07 CEST DavidGZ wrote:
> The opened file that makes Dlock to reject the
> locking attempt has always an "index" value 0 in the fcookie struct 

IIRC correct index 0 is used for the root directory. But may have to check.

**Comment by DavidGZ** [comment]
>IIRC correct index 0 is used for the root directory. But may have to check.

Yes, you're right. 0 is a normal value.

**Comment by th-otto** [comment]
Just found http://storage.atari-source.org/atari/personal/coldfire_packages/sysklogd-1.3-5.src.rpm. Is that the source you were missing?

**Comment by DavidGZ** [comment]
>Just found http://storage.atari-source.org/atari/personal/coldfire_packages/sysklogd-1.3-5.src.rpm. Is that the source you were missing?

No, he meant source packages from the Gentoo MiNT distribution done by Alan some years ago.

**Comment by DavidGZ** [comment]
OK, I think I finally know what's going on.

syslogd, portmap and inetd all of them spawned by init open some sockets, those sockets are added to the opened files list of those processes. When the sockets are created all the fcookie struct's members in the socket's file descriptor are initialized to 0 and left like this. Then when Dlock() checks the "dev"(the BIOS drive number) member in the fcookie struct for every opened file of every process, it finds that is 0 for the socket and it thinks that there is an opened file in the floppy drive (a:). When inet4.xdd was not loaded I guess no socket could be created and the problem was gone.

Now we need to think for a solution. I guess one is to initialize the fcookie struct for sockets and pipes with something.

**Comment by mikrosk** [comment]
Great investigation, David. And what a stupid bug. Maybe setting it to u:\ instead of a:\ (0) would make sense?

**Comment by th-otto** [comment]
I think it would be cleaner to fix the check in d_lock, to ignore cookies which don't have an fs ptr set.

**Comment by vinriviere** [comment]
@DavidGZ Genius!

**Comment by DavidGZ** [comment]
>I think it would be cleaner to fix the check in d_lock, to ignore cookies which don't have an fs ptr set.

I think this is the best solution.

Although a question arises about why the fcookie's fs member isn't filled for pipes seeing that there is a file system (pipefs) for them. I guess it was of not use.

**Comment by DavidGZ** [comment]
Fixed with:
[https://github.com/freemint/freemint/commit/529bb2b91821899971b07d7dafeb2b29d092833c](url)

While testing I found out something which seems wrong too.  See:
[https://github.com/freemint/freemint/issues/119](url)

**Comment by th-otto** [comment]
The links in the comment above are broken somehow... The first one ends with /url if i try to click on it

**Comment by DavidGZ** [comment]
>The links in the comment above are broken somehow... The first one ends with /url if i try to click on it

Fixed!

**Comment by ps68060** [comment]
Great investigation. I will test it as soon as I can 👍

**Comment by mikrosk** [comment]
The original reported has confirmed that the new build indeed works properly. Thanks @DavidGZ for great investigation & fix! Closing.
