### ISSUE TITLE
Make build system more consistent

### ISSUE THREAD

**Issue by mfro0** [freemint/freemint#12]
While the kernel and XaAES appear to support all the CPU subtargets (and compile all of them each run into their respective .compile($(CPU)) subdirs even if you usually only want one of them), this is not consistent elsewhere.

Some of the targets honour $(CPU) (and build only for the specified target), others completely ignore the setting and even try to compile incompatible asm and fail.

I'd like to see this changed into a scheme where either everything is build for all supported targets (using the .compile$(CPU) subdir method consistently everywhere) or only for the one specified. I'd prefer the latter. E.g. you would then just do

`M68K_ATARI_MINT_CROSS=yes CPU=ara make`

from the top dir and would get all the binaries for the specified $(CPU) subtarget **only**

**Comment by mikrosk** [comment]
Just for the reference, ideally the whole ecosystem would be like this:
- three platforms: ST (current 000), TT/Falcon/CT2 (030), AB040/Milan/Hades/CT60/Aranym (040,060,mil,ara) with feature autodetection
- make CPU=xxx, where xxx would be any value -mcpu= accepts (i.e. -m68000, m68020-60, m68060, mcpu=5475, ...)

So you could make your Milan build 040 optimised while your friend's CT60 build would be 060 optimised. Not sure about the FireBee, whether it needs a separate platform or not, right now 030/040 separation is needed because of the PMMU so this would imply that the FB needs another one as well.

But this is a future. Right now, having make CPU=xxx working would be more than enough.

**Comment by mikrosk** [comment]
Another strange inconsistency: Milan kernel is compiled for 020-60 (why not 040-60?) but it uses xaaes040.km (compiled for 040). On the other hand, TT/Falcon kernel is compiled for 030 but it uses xaaes030.km compiled for 020-60, WTF?

I know the speed difference is not the problem here (neither is compatibility, as all 020+ builds fall back onto 020-60 libgcc&friends), it's just another symptom of the aged build process.

**Comment by mikrosk** [comment]
@atic-atac are you sure you want this closed? I mean, my recent patches have improved some bits here and there but the ultimate goal, top level `M68K_ATARI_MINT_CROSS=yes CPU=ara make` is still not there (mostly because of the kernel build handling but also don't forget network drivers).

**Comment by atic-atac** [comment]
I didn't close it, github looks like it did based on the merge.

**Comment by paulwratt** [comment]
if you leave the CPU define so it can be used as an overrider by the dev and use either a MINT_TARGET_PLATFORM and/or a "make all-040" and "make all-supported", and fixup each "program" and "tool" to allow CPU and say INET_CPU for further levels of dev-user targeting.

Also does mint build with "../mint-master/configure && make", and if so, can it use different output folders?

**Comment by mikrosk** [comment]
While the build system is not behaving 100% as described in the posts above, I think this can be closed thanks to #348 (and all the previous work done to multi-CPU builds). Any further requests can be addressed separately.
