### ISSUE TITLE
1.19.x kernels require gemcon=false in N.AES config file

### ISSUE THREAD

**Issue by franklukas** [freemint/freemint#143]
N.AES do not longer work together with the MiNT Kernel 1-19. Keyboard inputs (press a key) not longer work. Mouse works fine. With the 1-18-0 Kernel all works ok.

**Comment by th-otto** [comment]
Did you try nohog.acc? Maybe its the same issue as with GEM=ROM, and N.AES runs in supervisor mode most of the time.

**Comment by franklukas** [comment]
Yes, I use nohog2.acc from 1-19-395. It makes no difference. When I press a key there comes a click sound but no letter.

**Comment by mikrosk** [comment]
When you try the oldest archived version (Mar 13, 2018) from https://bintray.com/freemint/freemint/snapshots/1-19-249 -- does it work?

**Comment by franklukas** [comment]
It do not work.

**Comment by mikrosk** [comment]
In that case it is an old regression, damn it. Personally I don't have a N.AES setup around :( There's good 5 years between 32cc8048 and 249f1e33.

**Comment by franklukas** [comment]
I try to send you my N.AES copy but it fails. Christian has it too I think ...

**Comment by mikrosk** [comment]
@DavidGZ this isn't related to the recent keyboard issues by any chance?

**Comment by DavidGZ** [comment]
I don't know, at first glance it doesn't look like, but I'll investigate it.
When was MiNT 1.18.0 released?
@franklukas when do you see this problem on which version of TOS is your setup running?

**Comment by DavidGZ** [comment]
> When was MiNT 1.18.0 released?

Answering my self, it was in March 2013

**Comment by franklukas** [comment]
Atari TT with german TOS 3.06

**Comment by mikrosk** [comment]
Confirmed here: https://www.atari-forum.com/viewtopic.php?p=402866#p402866

**Comment by lpgb** [comment]
Ran into this about a week or so ago on the V4. Set gemcon=false in the NAES config and the keyboard works. It's a workaround. This tip came from Olivier Landemarre.

**Comment by mikrosk** [comment]
I had some time and proper setup so I decided to bisect this one. The issue has nothing to do with keyboard handling, it was introduced in 9668d679 in Dec 2013 by obsoleting the `O_GLOBAL` flag used in `slip.xif`. 

Nearly exactly two years after that nobody else than Helmut found out the same as what I did today and even provided a fix: https://mikro.naprvyraz.sk/mint/201511/msg0014.html.

I have created a PR for this one, just in case: https://github.com/freemint/freemint/pull/379.

If nobody objects, I'll merge it and N.AES flies in 1.19.x again!

**Comment by mikrosk** [comment]
> The NAES docs explain what it does, but in German.

Just for the sake of completeness:

_If 'gemcon' = true, N.AES queries the keyboard using a special AES console device, which is automatically generated when N.AES starts. The output of the standard BIOS console device (device number 2) is redirected to this new AES device. This prevents the AES from losing characters if an application does not query the keyboard using AES functions. However, since some applications (in a somewhat improper way) hook deep into the operating system to query the keyboard and thereby render the device concept unusable, the generation of the AES console device can also be switched off. To do this, 'gemcon' must be set to false. In most cases, an incompatibility of an application is manifested by the fact that keyboard input is no longer possible._

That 'special device' is FreeMiNT's /dev/console but I'm not sure why N.AES developers thought it should be open with `O_GLOBAL` ...
