### ISSUE TITLE
'Integration' of libcmini into freemint

### ISSUE THREAD

**Issue by mfro0** [freemint/freemint#150]
Commit dcd1e73 and following are supposed to 'integrate' [libcmini](https://github.com/mfro0/libcmini) into FreeMiNT (originally to make COPS usable with and without MiNT).

As the original author of libcmini (or say, 'collector', because I freely admit that some of libcmini's routines are not my genuine own work but 'collected' from other OSS projects), I always said I'm happy to see any good use of libcmini for the Atari community.

However, I'm absolutely not satisfied in how this 'integration' has been done.

Thorsten has posted the 'integration' on the emutos mailing list only, for some reason.
For those that don't follow there, I copy my response over here:

> Thorsten,
> 
> 
> while I always said I wholeheartedly welcome every good use of libcmini, I really dislike the way you have 'integrated' it into freemint.
> 
> you appear to only copy the parts of libcmini you required, git history is lost, the library has been renamed without apparent good reason (why on earth do you think it needs a new name?), most hints of origin have been removed, no chance to reintegrate any improvements or bug fixes into original libcmini...
> 
> I think you are part of the Atari OpenSource scene long enough to know very well that 'fork-and-rename' is probably about the most effective way to act if you want to kill a project. It prevents reintegrating of changes/improvements and diverts the (already critically shrunken) Atari developer community.
> 
> libcmini is Open Source - so you are free to do with it whatever you want.
> 
> I do, however, think that (as a member of both projects) I have a say on what I think of this 'freemint integration': frankly, the way you did this is - IMHO - extremly counter productive and against all good manners.
> 
> The reasons you bring up do not - at least to me - justify that fork-and-rename in any way. There are other (better) ways to help mitigating your concerns (see my comments below).
> 
> I can't but think you are a victim of the 'not invented here - I can do better' syndrome?
> 
> Cheers,
> Markus 

You can probably see I was (at least a little) angry when writing this, and apologize if I wasn't exactly objective (calmed down myself in the meantime). I know (or at least hope) Thorsten has done this with best intent, nevertheless I essentially stand to what I said above.

I think this still can be (and must be) resolved in a beneficial way for both projects to avoid suffering from this fork-and-rename.

The best proposal I think I can come up with (provided the FreeMiNT developers community thinks it's mature enough to do so) is the 'official' offer to integrate the current (but uncrippled) state of libcmini into the FreeMiNT organisation (as a separate project) to allow both projects to benefit from this move.

This way you, Thorsten, would be free to integrate any required changes into libcmini without the need to wait for a new release and mutual dependencies/version conflicts could be resolved much easier. I would then close my own libcmini repository and link to the FreeMiNT organisation instead.

What do others think?

**Comment by vinriviere** [comment]
Generally speaking, putting important projects to the freemint organization is a good thing. Specially when projects interact between each other.

**Comment by th-otto** [comment]
I apologize to have you made angry, that surely was not my purpose.

>Thorsten has posted the 'integration' on the emutos mailing list only, for some reason.

Because i initially started on this to get a xcontrol clone usable for EmuTOS, and did not want to cross-post this in different MLs. BTW i'm not sure whether this is the correct place to discuss this either, since this is an issue tracker, not a discussion forum.

>The best proposal I think I can come up with (provided the FreeMiNT developers community thinks >it's mature enough to do so) is the 'official' offer to integrate the current (but uncrippled) state of >libcmini into the FreeMiNT organisation (as a separate project) to allow both projects to benefit >from this move.

I fear this will not solve some of the problems. First off, it does not allow to have reprodrucible builds. Secondly, it would not be easy to use it in local builds at all while developing, since it is in a separate repo (in snapshot builds that is solved by cloning it into a directory outside the freemint source tree, but you cannot assume that everybody has the same directory layout in his local copies).

**Comment by mikrosk** [comment]
> First off, it does not allow to have reprodrucible builds. Secondly, it would not be easy to use it in local builds at all while developing, since it is in a separate repo (in snapshot builds that is solved by cloning it into a directory outside the freemint source tree, but you cannot assume that everybody has the same directory layout in his local copies).

At least this one is easily solvable by making `libcmini` a git module within `cops` (or whatever else project).

As for the integration, with bearing in mind what I have written above, I think this is the right thing to do - Thorsten has a lot of freedom in freemint repositories so I don't think he would be pulled back. My only concern is what happens if @mfro0 will think that some change is "too much" and wouldn't be happy to accept it - so someone still has to be the maintainer who has the final word in situations like that.

Having said all of that, I still think we should kick `cops` and `hypview` out of `freemint` repository and maybe, along with Smurf, Phoenix, Highwire etc put all of them into a new organisation, something like [the orphaned project page](http://web.archive.org/web/20170514151609/http://www.ataricq.org:80/index.php?option=com_content&view=article&id=186&Itemid=76) years ago. Of course, this doesn't answer the libcmini question.

**Comment by mfro0** [comment]
> I fear this will not solve some of the problems. First off, it does not allow to have reprodrucible builds. 

Come on, that is only dependent on our (originally pretty arbitrary) decision on how we integrate libcmini releases into FreeMiNT builds. Back then, we decided to do that using a script that retrieves the latest release build for the link stage. That doesn't need to stay like this until eternity if it turns out to be impractical. It would be absolutely straightforward to link against a specific release specified in the Makefile and update this when needed.

>Secondly, it would not be easy to use it in local builds at all while developing, since it is in a separate repo (in snapshot builds that is solved by cloning it into a directory outside the freemint source tree, but you cannot assume that everybody has the same directory layout in his local copies).

Come on again. People handle the exact same problem with ease regarding mintlib and gemlib (and any other library that is part of the FreeMiNT organisation). Why shouldn't that work for libcmini as well?

**Comment by mfro0** [comment]
> My only concern is what happens if @mfro0 will think that some change is "too much" and wouldn't be happy to accept it - so someone still has to be the maintainer who has the final word in situations like that.

The only stipulation I would require as a precondition is that `libcmini` would still be independent from MiNT to make sure it stays usable for 'non-MiNT' code as well. I don't think that is too restrictive as the same is already accepted for mintlib. Other than that, I would be willing to rely on the common sense of the FreeMiNT organisation members.

**Comment by th-otto** [comment]
>I still think we should kick cops and hypview out of freemint repository and maybe, along with Smurf, Phoenix, Highwire etc put all of them into a new organisation

Out of the freemint repo: yes. The only thing that prevented me from doing this already is that i have no idea how to do that while keeping the history. But i don't think we need a new organization for this, it could just be a separate repo.

>It would be absolutely straightforward to link against a specific release specified in the Makefile and update this when needed.

And then update tons of Makefiles when something is changed is libcmini? That would be ridiculous. Using a submodule might work, though, I've rarely used that feature so far.

>People handle the exact same problem with ease regarding mintlib and gemlib

These are different: they are used from publicitly installed places. But you can't install libcmini there, because it has its own set of header files.

**Comment by mfro0** [comment]
> And then update tons of Makefiles when something is changed is libcmini?

For now, libcmini configuration settings are only in the toplevel `CONFIGVARS`. I don't see why this would need to change.

> These are different: they are used from publicitly installed places. But you can't install libcmini there, because it has its own set of header files.

I don't see the problem here, either. These places are just a convention. Define this for libcmini as well (like 'needs to be unpacked on the same directory level as the toplevel freemint directory') and you are all set.

**Comment by th-otto** [comment]
>settings are only in the toplevel CONFIGVARS

In the toplevel CONFIGVARS of freemint. But that is in a different repo. You cannot do changes to both of them with the same commit.

>These places are just a convention

No, they are not just a convention. They are the places where the compiler expects them. Otherwise automatic lookup of cpu-specific libraries does not work (which is IMHO a shortcoming of the compiler driver, it would need something like -Lsystem, just like -isystem for header files).

**Comment by mikrosk** [comment]
> Otherwise automatic lookup of cpu-specific libraries does not work

But this wont change in any case -- it doesn't matter whether you have a `minilib` folder somewhere or that the folder comes from a git module. So there is no point on arguing on this, libcmini has always been just an additional library, not something which should be installable instead of mintlib.

IMO the only question to be answered is there whether you feel that you need to have `libcmini` as part of `freemint` to be able to edit & use it quicker. If so, we can directly transfer its ownership (if @mfro0 agrees) and problem solved.

Btw, I have just created (locally) a separate COPS and HYPVIEW repositories and removed any trace of `tools/cops`, `tools/hypview` and `minilib` from `freemint`'s history. If you are fine with that, I can push it but I feel really sad that some commit messages will refer two wrong commit IDs after that. :(

**Comment by mfro0** [comment]
> In the toplevel CONFIGVARS of freemint. But that is in a different repo. You cannot do changes to both of them with the same commit.



> No, they are not just a convention. They are the places where the compiler expects them. Otherwise automatic lookup of cpu-specific libraries does not work (which is IMHO a shortcoming of the compiler driver, it would need something like -Lsystem, just like -isystem for header files).

Franly, I'm starting to suspect you arent't really interested in a solution, but rather want to argue about minor details?

There are lots of projects on github and elsewhere (virtually in the whole IT world) that manage independent development of libraries and applications that use them without any problems whatsoever.

To get your problems sorted (and ensure a future for libcmini as well), I offer to hand over libcmini under FreeMiNT organisational control that would give you full access and you see still fundamental unsolvable hurdles?

I'd like to ask you to make an alternate proposal, please.
A crippled, renamed libcmini in every application's development tree that uses it for sure isn't one.

**Comment by mfro0** [comment]
> At least this one is easily solvable by making `libcmini` a git module within `cops` (or whatever else project).

For me, git modules are a can of worms I'd rather kept closed with freemint (at least if we find another feasible solution). My personal experience with submodules is rather negative - in most situations, it will create more grief than benefit (at least if there is a simpler solution).

**Comment by vinriviere** [comment]
I've been told by a real Git expert that it was better to keep away from modules. I never tried them myself, though.

**Comment by mikrosk** [comment]
I don't have a strong opinion for or against, I have been using them for a few simple scenarios, couldn't complain. In this concrete case it would certainly solve Thorsten's fear about reproducible builds (the modules are references by commit ids).

Btw you can take a look at [cops](https://github.com/freemint/cops) & [hypview](https://github.com/freemint/hypview) repos now, if Thorsten has nothing against it, the git module in question would be only part of those repos, not `freemint`.

**Comment by th-otto** [comment]
> the git module in question would be only part of those repos, not freemint.

I've done changes also to nohog2 makefile, but this were merely a proof-of-concept, and could be reverted. The benefits there are minimal (except maybe adding the _stksize variable; i don't think that such a  small tools needs 64K stack).

**Comment by mfro0** [comment]
Who has the required access rights/authorization to create a new repository in the freemint organization (I don't seem to have it)?

**Comment by mikrosk** [comment]
You don't need to create anything - just transfer it to `freemint` organisation, I'll approve it if necessary.

**Comment by mfro0** [comment]
Thank you @mikrosk , did not recognize this button before. It appears to require repository create authorization in the target organization nevertheless, however:

> You don’t have the permission to create public repositories on freemint

**Comment by mikrosk** [comment]
Oh, interesting. I have made you an 'owner', hopefully it's enough. :D

**Comment by th-otto** [comment]
> I've been told by a real Git expert that it was better to keep away from modules

Did he explain why? Currently, it looks like the way to go

**Comment by vinriviere** [comment]
> Did he explain why? Currently, it looks like the way to go

I was a Git newbie at that time, so I didn't fully understood the arguments. But basically, the guy said that modules were a complex solution, and not particularly well designed. On the other hand, he was extremely enthusiast about other Git features.

So I have no concrete argument against modules.

**Comment by mfro0** [comment]
> Oh, interesting. I have made you an 'owner', hopefully it's enough. :D

Thank you, that worked. Congratulations, freemint org, you are now the proud owner of libcmini ;)

@th-otto @vinriviere [here](https://medium.com/@porteneuve/mastering-git-submodules-34c65e940407) is a good writeup that I find worth reading

**Comment by mikrosk** [comment]
@mfro0 thanks! I have made you a member of the kernel team, so you should have full access to `libcmini` as usual.

Now that we have `libcmini` at our disposal within `freemint`, I guess @DavidGZ could use it instead of his [slowly growing libcmini clone](https://github.com/freemint/freemint/tree/master/sys/usb/src.km/tos-common), too. ;)

**Comment by mfro0** [comment]
Tried to build today and noticed that it currently fails on my local environment and on Travis as well.

Reason is that recent gemlib changes are not available on the Travis environment.

Pretty much the same problem with gemlib that not only prevents freemint from building right now, but will also prevents reproducible builds later on.

My conclusion is that we need a more general mechanism that ensures each build has its correct library version assigned and available.
I'll open a new issue for that soon while I think we can close this one for now.

**Comment by DavidGZ** [comment]
> 
> Now that we have `libcmini` at our disposal within `freemint`, I guess @DavidGZ could use it instead of his [slowly growing libcmini clone](https://github.com/freemint/freemint/tree/master/sys/usb/src.km/tos-common), too. ;) 

From there only crtinit.c setstack.S and entry.S could be removed if we move to libcmini. Before it was true that TOS drivers were implementing its own libc functions [1] but last year I removed those definitions I make TOS drivers use the libkern ones [2], like the MiNT modules drivers do. In this case I think is a good idea to keep both drivers groups (TOS and MiNT) using the same library functions.

On the other hand since last year usbtool.c is using libcmini [3]


[1] https://github.com/freemint/freemint/blob/2ab8eccd9bb21808a6cb8026ceb7303112d2131c/sys/usb/src.km/global.h#L112
[2] https://github.com/freemint/freemint/commit/f11037a5273639e784c351038a59e0d09dd4028a
[3] https://github.com/freemint/freemint/commit/120e942cea8a652d28efc2ba3a1a5acd25c12b79#diff-e032464218231b15132896d437121923

**Comment by mikrosk** [comment]
> My conclusion is that we need a more general mechanism that ensures each build has its correct library version assigned and available.

It's not that bad, it's not like gemlib is updated every week. @vinriviere just needs to update his debian/ubuntu repository.

**Comment by th-otto** [comment]
One problem with gemlib is, that you cannot easily use it from a custom place; that would require to explicitly add the m68020-60 etc specific -L switches, just like with libcmini. And you cannot easily compile and install it in some travis scripts either, because at least some them are run without sudo privileges.

**Comment by vinriviere** [comment]
> It's not that bad, it's not like gemlib is updated every week. @vinriviere just needs to update his debian/ubuntu repository.

It would be nice that production processes don't depend from my private stuff. So I can hibernate if I want.

BTW, last time I tried to update the MiNTLib, I trashed my Cygwin environment 2 times. Because someone changed something in the structure of CONFIGVARS, or something like that. Not really friendly for maintainers. Updating sources is not so simple. I just gave up (until next time).

**Comment by mikrosk** [comment]
> And you cannot easily compile and install it in some travis scripts either, because at least some them are run without sudo privileges.

Which ones? The container-based architecture has been deprecated in 2018, all builds should now run in a separate VM. Then using sudo is easy: https://stackoverflow.com/questions/41165326/travis-ci-needs-root-privilege-when-using-go-test-how-to-set-it

**Comment by th-otto** [comment]
The kernel itself, see https://github.com/freemint/freemint/blob/2a0f350c92ca1a5e394b5a762dcdb9a1e68cbe14/.travis.yml#L4

**Comment by mikrosk** [comment]
Does it still work? In any case, we're free to remove that line.

**Comment by mikrosk** [comment]
I guess everything regarding libcmini done here, so closing.
