### ISSUE TITLE
Issue with naming scheme in snapshots?

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#167]
As noted in https://github.com/freemint/freemint/issues/92#issuecomment-621402134, I'm currently using a FreeMiNT snapshot downloaded in February 2020. I only know the folder name (1-19-9f3) and I wanted to figure out which exact commit this corresponds to.

Until now, I always thought that the last three characters (9f3, in this case) are the first three characters of the commit ID. With the (approximate) date this would be sufficiently unique to identify a commit.

However, **there is no commit in the entire year 2020 that starts with 9f3**. Could someone please check if the naming scheme is somehow broken, and therefore the folder in the auto-generated snapshot was not named correctly? 

Any other ideas how I could identify the commit?

**Comment by DavidGZ** [comment]
The commit is here [1], it's in a back up branch from the state of the repository before March. The reason why the commit is there is because Miro did a restructuring of the entire kernel repository, you can find the explanation and discussion about it here [2] 


[1] https://github.com/freemint/freemint/commit/9f3bd4766b150454be7fdd12a1d794431150ce65
[2] https://sourceforge.net/p/freemint/mailman/freemint-discuss/thread/CAN5rfbS%3D9gDnwS0hDDBS-OskyQTSJ%3DKNj%3DstrY-Kb1YFM1Op_Q%40mail.gmail.com/#msg36939369

**Comment by czietz** [comment]
Thank you @DavidGZ: It was not immediately obvious to me that I would have needed to look in the branch called _zzz-obsolete-master_. Now I know.

**Comment by mikrosk** [comment]
I feel your frustration @czietz, I really hope that was the last rebase done in this repo. Newer builds correspond to proper `master`, of course.
