### ISSUE TITLE
Compatibility with AES4.1?

### ISSUE THREAD

**Issue by dh219** [freemint/freemint#173]
Hi guys,

Sorry if this is an old topic, but couldn't see anything about it in the issues list.

I like XaAES and it seems very stable, but I also like the AES3/4 desktop rather than any third party offering. I spend half my time in MiNT and half in vanilla TOS. I'd like the desktops to be the same.

The obvious solution is to use AES4.1 I appreciate it's a bit slow, but I just like it.

Any version of 1.19 I've tried fails with what appears to be a stuck key. Clicking on File->Open shows a Hebrew character (looks like 0xDB?) filling the box rapidly.

This doesn't happen on the 1.18 release, but this, and all versions back to 1.15 fail in a more subtle way: quick repeated clicking of a window arrow or other window widget causes mouse click lockup. The desktop continues running and responding to keypresses, but it's as if the mouse button is permanently down so no further interaction with the window or menu is possible.

Is AES4.1 off the table entirely, is this a genuine bug (the key repeat one looks like it might be) or have I missed something stupid?

All these tests carried out with a vanilla system. /mint folder contains only one line: GEM=c:/aes41.sys.

Cheers,

DH.

**Comment by mikrosk** [comment]
No, actually it is good that someone finds time to test other AESes, too. Especially if it used to work with 1.18 release. 

It's interesting that the second bug happens also on older releases, 1.15.x specifically, because 1.15 doesn't have the new keyboard driver while 1.16 (IIRC) has so it's surprising that the symptoms are the same.

**Comment by dh219** [comment]
Hi Miro, Thanks for the reply.

I've put together a couple of test floppy images to show the problem(s):

[mintaes41.zip](https://github.com/freemint/freemint/files/4604300/mintaes41.zip)

The first is fairly obvious, let 1.19 (latest version from the build page) and AES4.1 boot to the desktop. Press 'O' for the 'Open' dialogue. The problem should be obvious.

The second problem can be seen with the 1.18 image. Again, let it boot to desktop, open a drive window then try rapidly and repeatedly clicking on one of the arrow widgets. Some times it only takes three clicks for the widget to become locked 'down' and that's the end of any mouse interaction with the AES. Keyboard events are still processed, however!

I've tested these cases both on real hardware (stock Falcon 030, 14MB, TOS 4.04) and in Hatari (Falcon configuration and 4MB STE TOS 2.06 configuration). It's consistent.

Currently I'm using MiNT 1.12 and AES4.1 on my Falcon, but the enhancements over the last 20 years in the FreeMiNT project (notably the EXT2 driver) are very attractive, but this window event lockup bug makes it unworkable.

Regards,

DH.

**Comment by EmmanuelKasper** [comment]
> The second problem can be seen with the 1.18 image. Again, let it boot to desktop, open a drive window then try rapidly and repeatedly clicking on one of the arrow widgets. Some times it only takes three clicks for the widget to become locked 'down' and that's the end of any mouse interaction with the AES. Keyboard events are still processed, however!

I can confirm this AES lockup, using the FreeMint disk image you posted.

On a FreenMint snapshot as of today with AES 4.1, I also noticed I could not open folders with double click.

**Comment by mikrosk** [comment]
According to https://www.atari-forum.com/viewtopic.php?f=14&t=39551&p=406157, MultiTOS 4.0 works.

**Comment by mikrosk** [comment]
Hi guys,

it took some time but I have some good news, too:

> The first is fairly obvious, let 1.19 (latest version from the build page) and AES4.1 boot to the desktop. Press 'O' for the 'Open' dialogue. The problem should be obvious.

This is the same root case as with #143 and therefore there's a fix pending. In my tests there were still some characters printed now and then but it's nothing compared to how it used to behave.

> The second problem can be seen with the 1.18 image. Again, let it boot to desktop, open a drive window then try rapidly and repeatedly clicking on one of the arrow widgets. Some times it only takes three clicks for the widget to become locked 'down' and that's the end of any mouse interact

Let me guess, you had memory protection enabled. With MP disabled, I can't reproduce the lockup => most likely a bug on AES 4.1 side.

> On a FreenMint snapshot as of today with AES 4.1, I also noticed I could not open folders with double click.

Indeed, this looks like a separate issue.

**Comment by mikrosk** [comment]
The random characters and double-click issues are now solved. However the lockup doesn't seem to be related to MP, I have managed to lock it up even without.

And since it goes all the way down to 1.15... I don't think there's an easy way to find out what's wrong. However I don't think it makes usage of kernels > 1.12 unusable, you can simple use up and down arrows instead of clicking on the widget.

**Comment by dh219** [comment]
Hi Mikro,

I've just tried the naes_fix branch in your repo and can confirm that the 'stuck key' bug does appear to have been fixed. Many thanks. 

The widget and menu lock up on widget use is indeed still there (even on a 68k) and may very well be an AES bug like you say.

Interestingly clicks on the desktop are still responded to (including the ability to open text files -- which sometimes unlocks things -- or to run programs -- which doesn't) but the menu and any other widget clicks are disregarded. Click to exit the VT52 text viewer also doesn't work.

I suspect there's enough information there for anyone who knows their way around GEM to speculate as to the problem, but that's a job for another day and, like you say, is probably only circumstantially related to freemint.

I don't suppose the default timeslice changed since 1.12 or something?

Anyway, thank you for this fix. I ran into this again only a couple of weeks ago as I often run MiNT in ST Medium resolution and XaAES isn't really usable below 640x400.

Will this make its way into the mainline build in time?

**Comment by mikrosk** [comment]
Oh, what a proactive approach! :-)

Indeed, AES 4.1 source code is available so yes, anyone dedicated enough can dig in. 

Time slices setting seems to be the same, see
https://github.com/totalspectrum/atari-mint/blob/309cfa3a9a4fa73aa352eb77335b80a906725d49/doc/appendix.c#L51-L55
vs
https://github.com/freemint/freemint/blob/e0133e6f98b00e02dcb1dcb5cf2eaea4d44bb611/doc/examples/mint.cnf#L81-L93

As for the ST Medium resolution usage in XaAES, see https://github.com/freemint/freemint/issues/360. Feel free to contribute your experience / ideas.

What do you mean "in time", in time for what? ;-) I need to rework that patch a bit because even the old implementation wasn't compatible enough, see e.g. here: https://mikro.naprvyraz.sk/mint/199801/msg00110.html. So I want to remedy that, too.

**Comment by mikrosk** [comment]
> This doesn't happen on the 1.18 release, but this, and all versions back to 1.15 fail in a more subtle way: quick repeated clicking of a window arrow or other window widget causes mouse click lockup.

Btw @dh219 I couldn't resist and tried to track this down, too. Surprisingly, the bug is quite recent, it was introduced sometime between 1.15.5 (works) and 1.15.10b (doesn't). However I have a hard time acquiring the versions inbetween so I can't tell you more. Ideally, if I could find also source archives, that way I could maybe even fix it.

**Comment by mikrosk** [comment]
@dh219 I guess you'll be pleased to hear that the AES 4.1 widget lock-up problem has just been fixed.

**Comment by dh219** [comment]
Apologies for taking so long to get around to testing this, but I'm very pleased to see a number of issues I've been following over the years all get closed at the same time.

<img width="300" height="241" alt="Image" src="https://github.com/user-attachments/assets/a1864d89-fef7-4574-8ec9-0bcdf8ebf44f" />

So here is SLIP working in ST Low resolution under AES4.1 (I know the 200 lines AES issue was with XaAES, but I couldn't put both in the same picture! ;) )

Many thanks Miro and the team for all the hard work!

David.
