### ISSUE TITLE
XaAES could cache converted textures

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#180]
This is clearly a feature request. While testing #171 I have noticed how awfully inefficient the texture handling is - it tries to load & convert like 20 images, one by one, so even on 32 MHz it takes good 10 seconds (!) to load.

XaAES could easily store prerendered textures into its `width` `height`.`depth` folder which has already some use.

**Comment by xdelatour** [comment]
**About texture cache:**
I'm trying to create a cache system but the converted images are much bigger than the original files (especially in 32-b true color, see below). I think this system should not be very useful since reading a large file should be slower than reading and decompressing a smaller file (but since I don't have a real machine I could be wrong). 

`file name (compressed size):  converted size (often four times bigger!)`
`dbox (15193): 61516`
`dbutton (47747): 65612`
`dtext (15193): 61516`
`outside (9245): 36940`
`info (8920): 15436`
`popbkg (24352): 124876`
`slide (15634): 65612`
`slider (11835): 36940`
`wtitle (9245): 36940`

In 256 color mode, the results are more ambiguous (5 files are smaller than the compressed files):

`dbox (30052): 49388`
`dbutton (18173): 16460`
`dtext (30052): 49388`
`outside (8166): 9292`
`info (15147): 16460`
`popbkg (30784): 58444`
`slide (19121): 16460`
`slider (11835): 9292`
`slwtitle (6092): 4172`
`wtitle (18173): 16460`

**About texture loading:** 
The 20 files are loaded in two different parts:
* 16 files are loaded in one file (win_draw.c, widget-related)
* 4 in another file (render_obj.c, theme-related)

AFAIK there is no parent structure shared between the two files, so they must be managed separately
If, to avoid making attempts to load all files, I browse the directory to look only for the available files, I must compare each of the names found with all the names of the possible files. (the idea is to set a flag for each existing file and then load only these ones)
Again, I don't know if this can save time.

Does anyone have better ideas than mine?

**Comment by mikrosk** [comment]
If I were implementing this, I'd create a static cache map with file name as key and binary blob as value. This binary blob would be created like this:
- check if the converted file isn't already available on disk
  - if it is, just load it
  - if it isn't, load & convert the source file and save it to disk. The latter operation would perhaps took some time by first use but that is fine.
- if the source file is not found, create key with NULL pointer

So no key = try to load it; key + NULL = file not found previously; key + non-null = use buffered bitmap.

As for the file sizes: even four times bigger bitmaps wont take 10 seconds to load, I assure you. :-) The biggest bottleneck was not loading but converting from what I could see.

**Comment by xdelatour** [comment]
Here is an attempt to implement a cache system : 
Requirements:
- Long filenames
- Create a new directory : `/var/cache/xaaes`
- Add `textures_cache=1` in xaaes.cnf

Files (patch and compiled kernel module)
- [textures_cache-20220612.patch.zip](https://github.com/freemint/freemint/files/9167308/textures_cache-20220612.patch.zip)
- [xaaes-20220718.zip](https://github.com/freemint/freemint/files/9167310/xaaes-20220718.zip)

**Comment by mikrosk** [comment]
@xdelatour I've created #271 for better clarity, I'll report my findings there.
