### ISSUE TITLE
Build failures with PRs

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#189]

**Comment by th-otto** [comment]
Something seems to go wrong when building PRs:

https://travis-ci.org/github/freemint/freemint/jobs/695761690#L292

toswin2 etc shouldn't be needed for PRS, and user name seems to be missing

**Comment by mikrosk** [comment]
Yes, this is an annoying bug. I course it's easy to add something like if (!pr) then download qed and stuff but annoyingly, the rest of the build depends on some of it as well.

Ideally, PRs should only build everything and not touch the deployment stuff. I have been thinking about disabling the preconfigured builds for PRs, to make my life easier -- one of the things we had lost when we switched to bintray is the ability to publish builds from PRs. :-(

**Comment by th-otto** [comment]
> one of the things we had lost when we switched to bintray is the ability to publish builds from PRs. 

You never should do that. As long as it is only a PR, there is no code base which includes it, so there is no point in deploying executables for it. Only reason to build PRs at all is to give us a hint whether that would break the build if we merge it.

**Comment by mikrosk** [comment]
>  Only reason to build PRs at all is to give us a hint whether that would break the build if we merge it.

I disagree. Having the option to actually *try* given feature/bugfix is one of the coolest things we could ask for. Too bad Github doesn't share my opinion here. :)

**Comment by vinriviere** [comment]
>  Having the option to actually _try_ given feature/bugfix is one of the coolest things we could ask for.

I agree. Having ready-to-use binaries for any source branch is the ultimate luxury.

**Comment by th-otto** [comment]
BTW i just noticed another problem in the script. When you really want to support that for PRs, then you must not pass the -u switch with an empty username to curl. If you do that, curl will prompt you for a name. You must omit the -u option completely.

**Comment by mikrosk** [comment]
OK, this should be "fixed" now. "fixed" because I have taken the lowest hanging fruit - just disabled the download and let Travis use Vincent's mintlib, pml, gemlib, cflib etc builds in case of a PR.

Also, it means there are four unnecessary builds done (the `VERSIONED` ones) but what the hell. Not perfect but surely better than an errored build for no reason. If github introduces something better for us, we can jump on it.

Oh and it will also work for forks, i.e. there wont be an attempt to download stuff for non-freemint pushes, making it easier to verify whether the build actually works on Travis (but it has a downside - it can complain about some outdated stuff in mintlib/gemlib etc as we had seen already).
