### ISSUE TITLE
kernel set up the cpu cookie wrong (PAK68/2) ...

### ISSUE THREAD

**Issue by franklukas** [freemint/freemint#193]
The MiNT kernel set up the cpu cookie at 030 with a PAK68/2 Speeder card wrong. My PAK has a 68881 FPU. When I disable the FPU MiNT set up the cpu cookie at 020 what is right. This is perhaps the same problem as EmuTOS has with the PAK68/2 ...  

https://sourceforge.net/p/emutos/mailman/emutos-devel/thread/1B5E3C32-0AE9-42C5-9AA4-6674777CD48D%40aol.com/#msg36973294

The USB Stack works not correct too. When the cpu cookie is at 030 loader.prg will load usb030.km. When the cpu cookie is at 020 loader.prg will load usb000.km. I rename the usb000.km to usb.km but I do not help.

Load kernel module: ...\usb000.km
usb loader: Fcntl(KM_RUN) failed!

System: 1040ST Mainboard, Lightning ST, Storm ST, PAK68/2
USB Driver LightningST Rev.268 MiNT Snapshot 07/2020

... by the way long files names in the archives are very annoying with real Atari TOS computers in the install process.

**Comment by czietz** [comment]
Here's the root cause I came up while investigating this for EmuTOS:
https://sourceforge.net/p/emutos/mailman/message/36984608/

In essence, an attempt to detect a 68030 by using PMMU instructions (e.g., `PMOVE`) does not work as expected on the PAK68/2. Therefore, FreeMiNT, which relies on that to set its _CPU cookie, misidentifies the 68020 for a 68030, with all consequences, such as the wrong kernel modules being loaded.

**Comment by th-otto** [comment]
On Freitag, 17. Juli 2020 19:02:27 CEST Christian Zietz wrote:
> In essence, an attempt to detect a 68030 by using PMMU instructions 

If i'm not wrong, that patch only addresses the sequence in the startup code, 
to prevent hangs/crashes there. But the cpu detection still uses 
pmove_from_tc(temp) https://github.com/emutos/emutos/blob/
c1cd074241aefa0d4f3760cc2c676e95426e8ef1/bios/processor.S#L99 

Doesn't that cause problems as well? Or at least identify 020+FPU as 030?

**Comment by czietz** [comment]
> Forget the other comment, too. The 020 case is already checked before, and the PMOVE is not executed there.

Even though you figured it already, for reference, here is what EmuTOS does to check for 68020:
https://github.com/emutos/emutos/blob/c1cd074241aefa0d4f3760cc2c676e95426e8ef1/bios/processor.S#L87-L97

It uses the `CACR` register and that works perfectly fine on the PAK68/2 - in contrast to FreeMiNT's CPU detection, which relies on `PMOVE` to tell 68020 and 68030 apart.

**Comment by th-otto** [comment]
Yes, i think that last part is the only thing that needs to be changed in mint.

@franklukas : just out of curiosity, could you try the attached sysinfo.app, and see if it correctly detects the cpu in your case? (there are two values, one is taken from the cookie which is most likely wrong, the other probed by own routines)

[sysinfo.zip](https://github.com/freemint/freemint/files/4941220/sysinfo.zip)

**Comment by th-otto** [comment]
@czietz could you please have a quick look at the attached patch whether you see anything wrong it? It changes the distinction between 020/030 the same way emutos does. It should also fix the (more hypothetical case) of a 68ec030 which currently was not detected and assumed to a have a pmmu, crashing in detect_pmmu(). Otherwise i could just push and let lukas test it ;)

[cpudetect.patch.txt](https://github.com/freemint/freemint/files/4941319/cpudetect.patch.txt)

**Comment by czietz** [comment]
Based on a cursory check, this looks right. However, I don't have a PAK. Testing and confirmation must be done by Frank.

**Comment by th-otto** [comment]
Ok, thx, pushed now, and build should be finished. @franklukas could you please test it?

**Comment by franklukas** [comment]
... what and how should I test exactly ?

**Comment by th-otto** [comment]
The latest kernel, it should not correctly set the CPU cookie to 020 on PAK/2, with or without FPU

**Comment by franklukas** [comment]
Thanks, it works fine now. The CPU cookie are set to 020 with the FPU aktiv ...

**Comment by th-otto** [comment]
Good. Did that also fix the issue with the usb loader? That could be a different thing...
