### ISSUE TITLE
[Feature request] Mint auto snapshot updates?

### ISSUE THREAD

**Issue by mzryz** [freemint/freemint#198]
Hi, I noticed that the man who makes Vision created an auto-update script for his program. I was wondering if it would be feasible to have something like this in Freemint? Could we have a small script that queries the bintray repo for latest version, using wget or curl. I think these days most Ataris running Freemint are connected to the net.

Just an idea.

**Comment by mikrosk** [comment]
Well, what you describe is quite easy to achieve using bash + some command line tools but realistically, people who have setup like this can `wget` and `unzip` the archive by themselves, or if someone creates such a script, it's easy to copy&paste. You can even find examples how to query latest snapshots from bintray in our scripts already: https://github.com/freemint/travis-scripts/blob/freemint-master/install.sh#L31

**Comment by wongck68** [comment]
Really I would not want to auto-update the MInt as there may be personalised settings in configs/directory structures. Recently I had that FAT32 issue, and if it auto-updated itself, I would not have a working "older" version. May be an MInt update is available annoucement.....
OTOH, auto update for installed RPM is good and I already done that 10 years ago for my system.    On Thursday, 27 August 2020, 08:05:06 pm SGT, mzryz <notifications@github.com> wrote:  
 
 


Hi, I noticed that the man who makes Vision created an auto-update script for his program. I was wondering if it would be feasible to have something like this in Freemint? Could we have a small script that queries the bintray repo for latest version, using wget or curl. I think these days most Ataris running Freemint are connected to the net.

Just an idea.

**Comment by th-otto** [comment]
> Really I would not want to auto-update the MInt as there may be personalised settings in configs/directory structures

Yes, that probably is the case most of time. But noone enforces you to use that image, you can just update your existing installation as before. It would just be an additional offer, and might help quickly checking new fixes if someone reports a problem.

> OTOH, auto update for installed RPM is good and I already done that 10 years ago for my system

From the sparemint archives? How did you auto-update them? An rpm binary is available again, but that is only responsible of managing the local database. To download the rpm archives from some network path you would also need something like yum or zypper.

**Comment by wongck68** [comment]
Just a bunch of scripts that will test for new versions of RPM and download them for installation. Nothing insane, would be the same if a human does it. It has been on my website HowTo for Mint for years now, recently I updated it during the lock down to work with Github since sparemint moved there.     On Monday, 31 August 2020, 09:33:41 am SGT, Thorsten Otto <notifications@github.com> wrote:  
 
 



Really I would not want to auto-update the MInt as there may be personalised settings in configs/directory structures


Yes, that probably is the case most of time. But noone enforces you to use that image, you can just update your existing installation as before. It would just be an additional offer, and might help quickly checking new fixes if someone reports a problem.


OTOH, auto update for installed RPM is good and I already done that 10 years ago for my system


From the sparemint archives? How did you auto-update them? An rpm binary is available again, but that is only responsible of managing the local database. To download the rpm archives from some network path you would also need something like yum or zypper.
