### ISSUE TITLE
XaAES crashes with memory protection without NVDI

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#22]
IIRC, in the b/w mode XaAES works fine as is. However in >=4 (?) colours it requires NVDI/fVDI to run. I think it shouldn't be too hard to detect this situation and warn the user appropriately.

**Comment by skaftetryne** [comment]
XaAES is working fine on my Milan without NVDI or fVDI in 8- and 16-bit modes. It is also working fine (but slow!) on my Mega ST with VOFA graphics card without NVDI or fVDI in 8-bit mode.

**Comment by mikrosk** [comment]
Interesting. Maybe it causes trouble only in EmuTOS?

**Comment by skaftetryne** [comment]
I'm sure I've had problems with XaAES on my standard Falcon with 4.04 and no graphics card. So there is a problem, just not sure exactly what.

**Comment by mikrosk** [comment]
Come to think about it, maybe the planar modes are the problem? I'll do some testing when I find time.

**Comment by skaftetryne** [comment]
Dug out my stock Falcon last night for a little bit of testing.

- XaAES works fine with the TOS VDI in mono.
- In colour accessories are loaded, but there's a bus error when apps (like the desktop) is loaded. Could not see any graphical/visual glitches.

On my STE with 8Mb alt-RAM and ET4000 graphics card:

- Works fine in both mono and colour on the graphics card with just Nova VDI.
- Works fine in mono on the shifter (could not test colour as I don't have a colour monitor at hand now), but only if alt-RAM is disabled. If alt-RAM is enabled and NVDI is not running, XaAES will crash upon launch. That is probably caused by blitting to/from alt-RAM.

**Comment by zabruder** [comment]
I don't think it's an XaAES-bug. I can reproduce it in aranym-mmu in 8 bit video. Applications crash in v_opnvwk (PC: 00E33BDA). Sometimes, sometimes not.  I can also reproduce it with TOS 3.06 on the TT with the TOS-VDI but haven't traced it there. Maybe the (Emu)TOS-VDI makes assumptions about the (Emu)TOS-AES opening the physical workstation or maybe it's just a stack-overflow.

**Comment by vinriviere** [comment]
I vaguely remember that long ago, XaAES crashed with EmuTOS VDI. This was because it calls AES appl_init() from supervisor mode. While this is generally considered as a bad thing, it should actually work fine. But this leaded to a stack overflow, and we finally added a workaround. I don't remember well, maybe the stack overflow problem appears again?

**Comment by zabruder** [comment]
It's the clients that crash, not XaAES and removing the apll_init does not change it.

**Comment by czietz** [comment]
@zabruder : I did also encounter crashes in v_opnvwk and came to the conclusion that the root cause was the 68030's memory protection or rather the VDI's lack of handling it correctly.

See, v_opnvwk in EmuTOS as well as in Atari TOS allocates memory in the context of the calling process, using its default protection settings -- so the memory may very well end up being "private". These memory blocks are organized as a linked list. So when the next process calls v_opnvwk, the VDI will try to walk this linked list of virtual workstations and will inevitably access the private memory from the other process, triggering the crash. 
A quick and dirty workaround might be to disable memory protection altogether. As for EmuTOS one can consider fixing this by making the VDI's memory allocation "global".

**Comment by mikrosk** [comment]
Great find, @czietz. I'm wondering whether there's a hope for us, TOS users on real  hardware. If I could count the number of questions about XaAES crashing due to lack of NVDI.. it gets asked quite often. Now thanks to @skaftetryne 's work on VanillaMiNT people are more or less aware of the NVDI dependency but generally speaking it sucks because a potential MiNT distro creator has basically two options: a) distribute NVDI (illegally) b) warn about it in the docs and answers 1000+1 questions why it doesn't work.

**Comment by czietz** [comment]
As for EmuTOS, the snapshot as of today contains a fix so that EmuTOS's VDI can be used with XaAES and memory protection on without crashing during v_opnvwk. 
Since those of us who didn't buy NVDI when it was still available are now effectively stuck without it, I think this was a worthwhile effort.

**Comment by mikrosk** [comment]
Fixed by EmuTOS 0.9.9 released a couple of days ago. By design in TOS VDI.

**Comment by mikrosk** [comment]
> I'm wondering whether there's a hope for us, TOS users on real hardware

Reopening this issue to remind myself and others about one discovery @th-otto has made: in https://github.com/freemint/freemint/blob/02ceb748073b6159ff4bf9929160bd1ed3ed85e1/sys/dosmem.c#L178-190 you can see there is a workaround to prevent exactly this kind of problem and yet it doesn't work.

**Comment by EmmanuelKasper** [comment]
I don't know what changed in the meantime, but running in ST low, medium and high resolution  with Freemint snapshot 2a88f753 on a 68000 STE with the TOS 2.06 VDI, xaaes and teradesk were stable enough for day to day use.

There are some graphic glitches in ST Low, and ST <edium due to Xaaes GUI elements having the wrong font size ( 2X too big), otherwise Teradesk, Sndplayer and the fileselector worked fine in my tests.

I used the disk image of my st mint distribution: http://www.subsole.org/static/retrocomputing/st_mint-0.8.img.zip

Attached Hatari Screenshot.
 
![grab0001](https://user-images.githubusercontent.com/1281908/67639577-d40ded00-f8f1-11e9-8850-58e91f85ec13.png)

**Comment by EmmanuelKasper** [comment]
BTW the font problem looks very similar to https://github.com/freemint/gemlib/issues/11
Is XAAES using gemlib ?

**Comment by th-otto** [comment]
Yes.

**Comment by mikrosk** [comment]
@vinriviere has promised this also in https://github.com/freemint/freemint/issues/106#issuecomment-474338729, one more reason to update it! :)

**Comment by th-otto** [comment]
There must  be some more to this than just the size set by v_opnvwk. If you look closer, you will notice that the menubar has the correct font, while the acc menu and the window gadgets use the 8x16 font. Also there seems to be something wrong with the calculation of the menubar height, looks like there is an area below the menubar that is neither part of the menu nor the desktop.

**Comment by th-otto** [comment]
It is getting more weird: when i boot directly into medium resolution (by using a video=3 option in xaaes,cnf), screen looks like 
![Screenshot_20191030_142437](https://user-images.githubusercontent.com/12425871/67863860-fb003500-fb24-11e9-83c6-6491efa3c2d4.png)

But when i switch to low, then back to medium resolution, menubar looks like

![Screenshot_20191030_144923](https://user-images.githubusercontent.com/12425871/67863930-1a975d80-fb25-11e9-983d-0fb222c6db47.png)

Even more funny, XaAES's own menubar seems to use a different fontsize:

![Screenshot_20191030_145502](https://user-images.githubusercontent.com/12425871/67864145-74982300-fb25-11e9-909b-a56262c5141a.png)

All these results are using current gemlib, with the call to vst_height() in v_opnvwk() removed. Also remember that this fix only affected v_opnvwk(), not v_opnwk().

**Comment by th-otto** [comment]
Please check if that fixes your issues.

There are still some minor glitches in low resolutions, like radio/checkbuttons being too large.

**Comment by EmmanuelKasper** [comment]
@th-otto how do I test this ? Is that enough to Boot with the latest Travis build ?

**Comment by th-otto** [comment]
For example,yes. It should also work  to just replace the xaaes.km  in your boot image.

There are some more issues, eg. the window title font is still too large (but it should not cause redraw issues like in the menubar)

**Comment by EmmanuelKasper** [comment]
OK I can confirm that the dual font size bug in Xaaes menu elements is fixed in 1-19-4d21842c. Great !
![grab0002](https://user-images.githubusercontent.com/1281908/67964761-16d90900-fc01-11e9-85e2-b278b1039d6d.png)

**Comment by th-otto** [comment]
>So looks like the ball is now in the emutos side :)

Hm, cannot reproduce that here, using a just-compiled etos256de.img. Switching resolutions also works. Maybe some program waiting for keypress?

**Comment by th-otto** [comment]
I think the height of the window titlebar cannot be changed easily to also use the 8x8 font on low resolutions. The titlebar can be themed, and images for the closer etc. are taken from a resource file. But that resource only has icons of 16x16, so using a smaller font would not help because the bar still has to be large enough to also contain the icons (unless the window only has a name but nothing else, but that is rather rare). Same goes for the vertical/horizontal sliders, which have to be wide enough to contain the arrows/sizer.

Guess we have to live with that. Using such low resolutions isn't much fun, anyway.

**Comment by EmmanuelKasper** [comment]
OK since we found that current xaaes works with the Ste TOS VDI and emutos VDI, thus not requiring nvdi, should we considered the Problem as fixed and close this bug ?

 The only thing I saw missing, is a report of a Falcon user stating that xaaes works correctly with the ROM vdi.

**Comment by DavidGZ** [comment]
> The only thing I saw missing, is a report of a Falcon user stating that xaaes works correctly with the ROM vdi.

I can test with a Falcon in 030 mode. I've tested with the latest snapshot (the ST package because my Falcon doesn't have a FPU), at first glance everything seems OK, slow but fine :-) , resolution tested 320x240x 16 colours, 640x480x 4 and 16 colours.

Do you want me to test anything specific?

**Comment by mikrosk** [comment]
@DavidGZ that's interesting. Can you test, say, 640x480@256c ?

Also, do we really need FPU to run m68020-60 builds? I can't imagine why it shouldn't run without FPU.

**Comment by DavidGZ** [comment]
> @DavidGZ that's interesting. Can you test, say, 640x480@256c ? I can't really see from the comments here what has changed to make it work, @th-otto did you do something?
> 

Just tested it, it works too.

> Also, do we really need FPU to run m68020-60 builds? I can't imagine why it shouldn't run without FPU.

Now I think one of the culprit is toswin2, because I think the message "this binary can not run without a FPU" comes from MiNTlib, but it could there be some other reasons. I'll try again later.

**Comment by mikrosk** [comment]
Ah, I get it now guys. You are all testing it without memory protection, aren't you.

@DavidGZ yes, that must come from toswin2, neither the kernel nor xaaes uses mintlib.

**Comment by th-otto** [comment]
Yes, the things i fixed recently were related to font sizes in low/medium resolution (should actually have been a separate issue,but was reported here). So this issue shouldn't yet be closed (at least i think so, the initial problem was caused by emutos vdi accessing some pointer that might belong to a different app when closing a workstation; iirc that has already been fixed in emutos, but the workaround in the mint kernel still does not work).

**Comment by DavidGZ** [comment]
> Ah, I get it now guys. You are all testing it without memory protection, aren't you.
>

Yes I was, my test was with the 000 snapshot so it's not possible to enable memory protection with the kernel within. With the Falcon,TT,Clones package and after I disabled the load of toswin2 from xaaes.cnf, the test failed with memory protection enabled and succeeded with it disabled. With memory protection it fails to load Teradek and you end up in the XaAES shell where is not possible to load any application from its menu.

@mikrosk Why do you think this is related with the VDI?

**Comment by th-otto** [comment]
It was caused when opening/closing VDI workstations. Some VDI update a link pointer in the workstation structure. But the other structure is usually owned by a different process, because the VDI does a Malloc() for it.

**Comment by DavidGZ** [comment]
Oops...sorry, I should he read the issue's thread carefully. Thanks for the info.

**Comment by EmmanuelKasper** [comment]
If the bug report only applies to Freemint with Memory Protection, can we retitle the bug ? It makes non mp users feel safer to use xaaes ;)

**Comment by mikrosk** [comment]
Yeah, I confirm the bug is still here, in both 030 or 060 (with MP enabled).
