### ISSUE TITLE
Daynaport driver support for RaSCSI

### ISSUE THREAD

**Issue by mzryz** [freemint/freemint#229]
Using latest HD-Driver 11 & Mint 1.19-CUR.
Attempting to use Daynaport over Wifi bridge doesn't work. I have put the scsilink.xif into the mint directory with all other XIF files, the driver is loaded and fully detected during boot on en0, so the driver DOES see the device. The Daynaport is also detected by HD-DRIVER and is on ID 6. I ran auto-configuration also.
Using E-NICK to configure the Mint network I set:
IP Address (static): 10.10.20.2
Router Address: 10.10.20.1
Subnet Mask: 255.255.255.0
DNS Server: 1.1.1.1
Rascsi Dayna mounted as such:
rascsi -ID 6 -t scdp wlan0:10.10.20.1/24

But when accessing anything on the internet, ie; ping www.google.com etc, the system completely locks for over 5 minutes, sometimes permanently. No results found. Also tried updating NTP date, after 5 minutes it returns it cannot access the network.

I configured everything through easysetup.sh.

I have opened an issue on the RaSCSI side, but Uwe thinks this is a mint issue. @anodynesoftware perhaps you might advise? Thank you

https://github.com/akuker/RASCSI/issues/279

**Comment by anodynesoftware** [comment]
On 28 Sep 2021 at 10:04, mzryz wrote:
> 
> I have opened an issue on the RaSCSI side, but Uwe thinks this is a mint
> issue. @anodynesoftware perhaps you might advise? Thank you
> 
Actually I don't even understand the chain of devices that you're trying to 
use.  But in any case, I'm really not the right person to ask about this.  I 
think you need somebody to advise on tracing within FreeMiNT, to disover who is 
dropping the ball.

Roger Burrows

**Comment by mikrosk** [comment]
I suggest you to find someone with a real Daynaport device (@franklukas IIRC). The driver used to work nicely.

**Comment by mzryz** [comment]
@mikrosk is there something I can do to try and see 'under the hood' what is causing the issue? As I don't know whether it is the driver, or whether it is the configuration of the Rascsi device. (I'm assuming people know what a Rascsi is, if not check it out it is amazing... Especially you @anodynesoftware ! being a scsi man)

**Comment by mikrosk** [comment]
Well, you can always try the original drivers, or drivers for Sting: http://www.anodynesoftware.com/ethernet/main.html

**Comment by uweseimet** [comment]
I don't think one can link issues in different projects, so I copied my comment from the rascsi project, see https://github.com/akuker/RASCSI/issues/279.

@mzryz You can enable log level "trace" (by starting rascsi with "-L trace") to get some analytic output, in order to see which SCSI commands are sent by the Atari driver. Since the Daynaport emulation is working fine for Macs there might be an issue with the Atari drivers, or just with the driver setup. Or some functionality required by the driver is not yet emulated. Roger Burrows should be able to help here, because he has implemented Daynaport drivers in the past. I did not succeed in getting his drivers working with my TT (under MagiC) and a Riebel VME network card, though, probably because I could not find any up to date setup instructions. I would have tried the Daynaport emulation next, but first wanted to have a valid setup with real hardware, i.e. with the Riebel card.

**Comment by mzryz** [comment]
I ran slinkctl.ttp diagnostics by @anodynesoftware I'm hoping Roger can help me interpret the results.
![PXL_20210929_191509750](https://user-images.githubusercontent.com/23113373/135334155-9a367113-1a69-4b46-a72a-df1e5250a190.jpg)

**Comment by mzryz** [comment]
Here is the output of ifconfig on the RaSCSI:
`pi@rascsi:~ $ ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 71  bytes 4135 (4.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 71  bytes 4135 (4.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

rascsi_bridge: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 10.10.20.1  netmask 255.255.255.0  broadcast 10.10.20.255
        inet6 fe80::809a:80ff:fe30:3698  prefixlen 64  scopeid 0x20<link>
        ether 00:00:00:00:00:00  txqueuelen 1000  (Ethernet)
        RX packets 93  bytes 4278 (4.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 152  bytes 10744 (10.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.51  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fd51:42f8:caae:d92e::ff  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::4579:c572:ae6c:fc26  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:fe:3d:55  txqueuelen 1000  (Ethernet)
        RX packets 2659  bytes 317399 (309.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 448  bytes 66628 (65.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
`

**Comment by mzryz** [comment]
Struggling to work out how to enable the -L trace that Uwe recommended. I am trying 'systemctl start rascsi -L trace' but this doesn't work. Could you be more specific thank you & will the result be logged somewhere? Thanks.

**Comment by mikrosk** [comment]
Not sure why are you trying such hard weapons as the first thing.... try that Sting drivers first, that will tell you whether your device or freemint is the culprit.

**Comment by mzryz** [comment]
@mikrosk because I simply have never used sting before and I know my Mint configuration works perfectly with my Netusbee. All I am doing is enabling / disabling the interface XIF files and then amending the IP/interface/route with E-nick. Really the only difference between my working Mintnet TCP IP and not working is the different interface drivers.

**Comment by anodynesoftware** [comment]
On 29 Sep 2021 at 12:17, mzryz wrote:

> I ran slinkctl.ttp diagnostics by @anodynesoftware I'm hoping Roger can help
> me interpret the results.
> ![PXL_20210929_191509750](https://user-images.githubusercontent.com/23113373/1
> 35334155-9a367113-1a69-4b46-a72a-df1e5250a190.jpg)
> 
It's been a long time (> 10 years) since I looked at this, but the source code 
in the freemint repo tells you what's going on as far as the driver is 
concerned.

The driver saw 50 input packets, of which 40 were ignored because they had an 
invalid length (that means the length of the ethernet data itself was either 
less than 60 bytes or more than 1514 bytes).  I have no idea if that is normal 
behaviour for your device - for a real DaynaPort it seems like a high number of 
invalid packets.  But as I say, I've not looked at this for a very long time.

The driver wrote 41 packets without problems.

The device did not report any errors.

However, I still don't understand how you've got your system set up.  If you 
want me to continue to look at this, please provide a connection diagram with 
all the bits and pieces used (hardware & software), starting at your Falcon:

FreeMiNT --> SCSILINK.XIF --> Falcon SCSI port --> ???

Roger

**Comment by mzryz** [comment]
@anodynesoftware 
I am attempting to use a RaSCSI Daynaport emulator. It is a raspberry Pi powered device, please see this:
https://github.com/akuker/RASCSI/wiki/Dayna-Port-SCSI-Link

As you can see and hopefully appreciate, this would be very useful for many Atari owners in getting wired/wireless Ethernet to their machines. Apparently it is working perfectly with Apple Macs already.

**Comment by mzryz** [comment]
![rascsi_daynaport_wireless](https://user-images.githubusercontent.com/23113373/135436340-462e6950-933e-4659-80a4-ecf197d8a205.png)

**Comment by mzryz** [comment]
@anodynesoftware No problem - please appreciate that I never intended to open an issue log here in the first place. It was @uweseimet who suggested the problem was on the Atari side, not on the RaSCSI side. I am just an enthusiast who likes to try and see Atari get some of these great devices that Apple and Amiga uses benefit from. Closing topic.

**Comment by uweseimet** [comment]
Well, we don't know on which side the problem is, do we? Anyway, I am not maintaining the RaSCSI Daynaport code anyway, so somebody else would have to follow up on this.
