### ISSUE TITLE
APPL_GETINFO_STR() returns incomplete data (text)

### ISSUE THREAD

**Issue by GokMasE** [freemint/freemint#238]
APPL_GETINFO_STR(), which is an extended mode of APPL_GETINFO() (ag_type=96), does not return all the text data as suggested by TOS.HYP. The buffer pointed to by ap_gout3 should be filled in with the following upon a successful call:

- **"asci version|development status| architecture target| build date & time| compiler used"**

However, what I see returned is simply

- **"build date & time| compiler used"**

Source: https://freemint.github.io/tos.hyp/en/appl.html#appl_getinfo_str

**Comment by xdelatour** [comment]
The related code is in the file '/xaaes/src.km/info.c', lines 55-61. Only date, time and compiler are set.  
Lines 39-53 are disabled, perhaps because version is undeclared.

Things looks OK if 'version' is changed with 'AES_ASCII_VERSION'.

In xa_appl.c (line 1543), strings are filled if pb->control[N_ADDRIN] >= 3 but should be if pb->control[N_ADDRIN] == 4 according to the documentation (newcalls.txt).

**Comment by lpgb** [comment]
Was working with this call today. It also appears ap_gout1 is padded on the wrong side. Docs indicate left-aligned, it seems to output right-aligned.

**Comment by xdelatour** [comment]
TosHyp seems to be wrong: [newcalls.txt](https://github.com/freemint/freemint/blob/master/xaaes/src.km/newcalls.txt#L133) says AES ID is right-aligned.

**Comment by lpgb** [comment]
That explains ap_gout1. Can someone with write access correct toshyp?

**Comment by xdelatour** [comment]
I don't have write access, and don't know how to use PR anyway.
Here is an attempt to fix ap_gout3 (and the build date in the About dialog box which is wrong too because the same info_string is displayed):

- xversion.sh: replaces %H:%M with %H:%M:%S (BDATETIME used in info.c only)
- info.c: fixes info_string to match doc from newcalls.txt (but m68k is never used, m68000 is returned - ASCII_ARCH_TARGET from version.h)
- about.c: replaces info_string  with BDATETIME (ABOUT_DATE in the About dialog box)
- xa_appl.c: N_ADDRIN should be equals to 4 (instead of >= 3)
[xversion.sh.patch.txt](https://github.com/freemint/freemint/files/8007706/xversion.sh.patch.txt)
[about.c.patch.txt](https://github.com/freemint/freemint/files/8007707/about.c.patch.txt)
[xa_appl.c.patch.txt](https://github.com/freemint/freemint/files/8007711/xa_appl.c.patch.txt)
[info.c.patch.txt](https://github.com/freemint/freemint/files/8007712/info.c.patch.txt)

**Comment by GokMasE** [comment]
For the record, this bug is not present in XaAES-Ozk (See https://github.com/freemint/freemint/issues/241)

Someone still needs to update TOS.HYP to correct the section regarding [APPL_GETINFO_STR()](https://freemint.github.io/tos.hyp/en/appl.html#appl_getinfo_str) where it says that the AES ID should be left aligned - according to [newcalls.txt](https://github.com/freemint/freemint/blob/master/xaaes/src.km/newcalls.txt#L133) this string is supposed to be right aligned)

**Comment by mikrosk** [comment]
@xdelatour your patch _almost_ solved it :) This is what I got when applied your changes:

![snap000](https://user-images.githubusercontent.com/3062260/173182836-d963a58d-6858-4fa6-a0f2-f008d56936eb.png)

First I thought that it is some kind of C string corruption but when looking closely I realised that it is "jún" in UTF-8, i.e. "June" in Slovak (my native locale). Adding `LC_ALL=C` in `xversion.sh` solved it.

Thanks for your contribution!

**Comment by mikrosk** [comment]
> Someone still needs to update TOS.HYP to correct the section regarding [APPL_GETINFO_STR()](https://freemint.github.io/tos.hyp/en/appl.html#appl_getinfo_str) where it says that the AES ID should be left aligned - according to [newcalls.txt](https://github.com/freemint/freemint/blob/master/xaaes/src.km/newcalls.txt#L133) this string is supposed to be right aligned)

This has been fixed in https://github.com/freemint/freemint/commit/a668dc4d#diff-b3cd89d6eea7218d92ddc3e8d15fc3c4d30449d7cb3357f5742c84b73c7d1344L90 but didn't make it back to TOS.HYP author(s) :) Fixed in https://github.com/freemint/tos.hyp/commit/f28d19571f2f61892a985ca1266cf5f0c056d551.

**Comment by GokMasE** [comment]
Very nice!

Thank you @mikro and @xdelatour - another one bites the dust :)
