### ISSUE TITLE
Improvements in mint.cnf (xaaes.cnf) parsing

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#32]
I can think of two major improvements:

- allow usage of relative paths i.e. if mint.cnf is located in `c:\mint\mint-123\mint.cnf` it wouldn't complain about executing binaries relative to that (or $SYSDIR -- perhaps easier) path
- allow usage of either real env variables or some faked ones -- $SYSDIR and $MCHDIR are obvious candidates (this reminds me introduction of $MCHDIR as an env variable...)

With at least one of the changes one could use universal configuration files across different builds, esp. true for `INIT`/`GEM` and `xaloader.prg` path.

**Comment by paulwratt** [comment]
this is definitely a candidate for a v1.20 release.

note that ENV parsing should be on per line basis, not per file, as both MiNT and XaAES define ENV variables through out there configs.

**Comment by th-otto** [comment]
Environment variable parsing has now been implemented in https://github.com/freemint/freemint/commit/8f23fa118809e9f5dfec0d572a8250e9d0e7e3d4. Only real environment variables are supported (ones that are set using setenv, not any local ones that are just assigned as in `KERN_DEBUG_LEVEL=1`). 

`$SYSDIR` was already set in https://github.com/freemint/freemint/blob/8f23fa118809e9f5dfec0d572a8250e9d0e7e3d4/sys/init.c#L1080, i've also added a few others like `$MCHDIR`, `$MINT_VERSION`, and `$BOOTDRIVE`

There is one thing that may behave differently than before: in the previous version, all need conversions (like stripping quotes, convert escape sequences) was done to the same buffer the one the file contents were read to. That worked because it would never write more bytes, only fewer. When implementing this, i had to use fixed line buffers instead. That means, input lines are now silently truncated if they are too long. The size is currently set to 512, so i think this is not a real problem in practise.

The doc/example/mint.cnf has already been adjusted accordingly, and the sysdir tool should no longer be needed (it is still build and installed though, for the the per-cpu builds, where mint.cnf is not updated).

**Comment by mikrosk** [comment]
Nice! 

I just wish you separated whitespace changes from the actual implementation, now the diffs are huge and very hard to review. :-/

>  (it is still build and installed though, for the the per-cpu builds, where mint.cnf is not updated)

If the issue is that mint.cnf from some older CPU build would reference to sysdir.tos, this is OK: sysdir.tos was unpacked to c:\mint. So if you already have it: good. If you don't have because you are installing from scratch: also good, you have to use the new mint.cnf.

**Comment by mikrosk** [comment]
Implemented by 8f23fa118809e9f5dfec0d572a8250e9d0e7e3d4, to tested.

**Comment by uweseimet** [comment]
Do I understand correctly that with this change you can unpack the base archive on different drive than C:,? I can then install MiNT without a conflict with my regular setup. and would be able to boot it just by selecting the installation drive as boot drive?

**Comment by mikrosk** [comment]
As you will be literally the first person to try it out, some caution is justified but yes, everything seems to be prepared for such scenario.

**Comment by uweseimet** [comment]
The respective ZIP package is not available before tomorrow (nightly build) I assume?

I mentioned it elsewhere, but anyway: Any chance to get mkfs.ext2 included in the base ZIP? This would make it easier not to use FAT32 for long filenames, but to use ext2 instead.

**Comment by mikrosk** [comment]
It's available after every commit: so feel free to download https://tho-otto.de/snapshots/freemint/bootable/freemint-latest-02060-tt_falcon_clones.zip.

Inclusion of mkfs.ext2 is certainly possible, it needs to be either built from https://github.com/freemint/e2fsprogs/commits/mint-1.42 or downloaded from http://vincent.riviere.free.fr/soft/m68k-atari-mint/archives/mint/e2fsprogs (perhaps easier).

**Comment by uweseimet** [comment]
I unpacked the current archive on an otherwise empty drive K:, and this time I could boot properly from K:, simply by pressing "K" when booting. I have not not run further tests, though, except for manually launching bash.
First-time users will surely appreciate not having to discard their current drive setup just to try out MiNT, like it was before.

**Comment by mikrosk** [comment]
Awesome, thanks for the test! I'll update the documentation (freemint.stg) and we can close this one.
