### ISSUE TITLE
Include mkfs.ext2 / fsck.ext2 into bootable builds

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#356]
Perhaps the most easiest way is just grab http://vincent.riviere.free.fr/soft/m68k-atari-mint/archives/mint/e2fsprogs and put it into `.scripts`, same as we do with bash and coreutils.

**Comment by th-otto** [comment]
Implemented now by https://github.com/freemint/freemint/commit/365fd5b7ce538618fd0ded3de4fe1df31652fdc3 (and a small fix in https://github.com/freemint/freemint/commit/2eb11cd0e12365d9e9f8bce9ed7e5a7da1c6710a).

Although, after thinking again about this, i really wonder whether we really need those tools in the bootable builds. There is no harddisk image or something like that with an ext2 partition. Maybe we could add one, but that would only make sense for aranym, not for the st/ste/tt builds. And it would make updating that image with the binaries more complicated.

The tools were compiled from the 1.42 branch of e2fsprogs . I also created a new 1.47 branch with the current version of the tools, but did not test them yet.

**Comment by mikrosk** [comment]
Not sure why do you think of an image as the first use case? Clearly this is for users which marked some partition as "RAW" or "LNX" in HD Driver and want to create an ext2 partition afterwards (as HD Driver doesn't format such partitions as it does with BGM/F16/F32).

**Comment by th-otto** [comment]
Yes, but i always thought of the bootable builds as something to "get you started". For a full installation, you also need a lot of other things, most notably the rest of coreutils. I don't think that we want to add all that already to the builds.

BTW, is HDRUTIL able to create & initialize a FAT32 partition? Otherwise, we would have to add some dosfstools, for the same reason.

**Comment by uweseimet** [comment]
@th-otto Yes, HDDRUTIL has supported creating FAT32 filesystems when partitioning for a very long time.

Regarding ext2fs I just noticed that with the base installation you cannot create an ext2fs, but you can (e.g. with HDDRUTIL) create FAT32 partitions. IMHO if you want users to prefer ext2fs, they should have the means to create ext2fs without having to install additional packages. Otherwise they might just create FAT32 partitions, which are a less good choice with MiNT.
This is why I suggested to add mkfs.ext2 to the archive.

**Comment by mikrosk** [comment]
In the end I have included only a very minimal set of the tools - fsck, label and check; same as we do for fatfs. It makes the archive smaller and simpler.

Thanks Uwe for the push, before this change I used ext2 partitions only alongside EasyMiNT (a full-blown distro) and while I could access my partitions thanks to `ext2.xfs`, as soon as didn't cleanly shut down the system, I was "forever" (until I again boot into EasyMiNT...) cursed with the unchecked fs warning.

Now it's just about uncommenting one line in mint.cnf:
https://github.com/freemint/freemint/blob/3ca500d8bb756aa1f88ca065ca0b44774047533f/doc/examples/mint.cnf#L377
Very handy!
