### ISSUE TITLE
TOSWin 2.7 saved settings not applied when only console settings

### ISSUE THREAD

**Issue by wongck68** [freemint/freemint#52]
So I delete the CFG file from the TOSWIN2 folder and the console default to white font on black background on start up after a reboot.

I changed the font, foreground and background colour, save the settings. I see the CFG being saved.
Reboot.... and when console comes up, it's font is white with black background.
I open the window config.... the font & colours that I chosen are shown!! So the settings are read but the settings are just not applied.

If I now open bash, makes some windows settings changes, and save it. On startup, the console will take on the settings as specified in the CFG file.
I tried to simulate the effect by deleting the bash config section in the CFG but the console settings are still being applied on start up after a reboot.

Looks like if only you have console settings saved, the settings are not applied on start-up.
This is with freemint-1-19-95d-col.

**Comment by mikrosk** [comment]
I've looked into this, it's actually... a feature. A bit broken but still useful.

TW2 maintains some kind of profiles -- so you can have different colours when starting the console, /bin/bash and /your/custom/script.sh. So far so good.

However it's very easy to mess the profiles up because TW2 uses only one global variable for window configuration -- so if you open the default profile (no windows) and save it while /bin/bash is open, the cfg file will look like:
```
...
WinCfgBegin "default"
...
WinCfgEnd "/bin/bash"
...
```
therefore ignoring your bash settings. So if you want to define global (default) settings, do that with all windows closed (and start without any cfg file first). Then, if you want special settings for /bin/bash, open the shell, go to the settings, change & save. This way you should see two sections in your cfg file, default & /bin/bash.

Not perfect, not even nice but it's not a bug per se.

**Comment by mikrosk** [comment]
@th-otto sure it can be improved, no question about that. Particularly TW2 is full of things to improve. ;-)

**Comment by wongck68** [comment]
For me, I have my windows open when I do the settings, and I save the settings without closing the window.I expect all the settings that I change for both opened and closed windows to be saved.  

LOL... So manually editing would still be the best, because you get what you edited.. :-) 

    On Tuesday, 20 June 2017, 7:57, Miro Kropacek <notifications@github.com> wrote:
 

 @th-otto sure it can be improved, no question about that. Particularly TW2 is full of things to improve. ;-)—

**Comment by wongck68** [comment]
I only use console and bash, I have 3 profiles... 1 default, 1 console and 1 bash.Thanks, I never knew how to change the default profile, now I know. ;-) 

    On Tuesday, 20 June 2017, 6:40, Miro Kropacek <notifications@github.com> wrote:
 

 I've looked into this, it's actually... a feature. A bit broken but still useful.TW2 maintains some kind of profiles -- so you can have different colours when starting the console, /bin/bash and /your/custom/script.sh. So far so good.However it's very easy to mess the profiles up because TW2 uses only one global variable for window configuration -- so if you open the default profile (no windows) and save it while /bin/bash is open, the cfg file will look like:...
WinCfgBegin "default"
...
WinCfgEnd "/bin/bash"
...
therefore ignoring your bash settings. So if you want to define global (default) settings, do that with all windows closed (and start without any cfg file first). Then, if you want special settings for /bin/bash, open the shell, go to the settings, change & save. This way you should see two sections in your cfg file, default & /bin/bash.Not perfect, not even nice but it's not a bug per se.—
