### ISSUE TITLE
inet4.xdd missing in actual snaphot builds

### ISSUE THREAD

**Issue by Nervi** [freemint/freemint#58]
Hallo,

today I wanted to try the actual snapshot build of MiNT 1.19.x and I discovered that the inet4.xdd is missing in the build. The snapshot builds of freemint.org are also affected. I think there went something wrong in the compiling process. May you fix that bug and take care of the integrity of the snapshot builds?

Andreas

**Comment by czietz** [comment]
Contributing the analysis I posted in the Atari-Home forum: Judging by the Travis build logs, inet4.xdd is still present in job 119 (https://travis-ci.org/freemint/freemint/jobs/242208106) but isn't anymore in job 120 (https://travis-ci.org/freemint/freemint/jobs/242208513). So one can assume that this was caused by the Makefile modifications of commit https://github.com/freemint/freemint/commit/80d872652e32be9d9d032413defe8262a47bbf68

**Comment by mikrosk** [comment]
Thanks for reporting! Commit 0dff205f should fix that, i.e. correct build should be available in a few minutes.
